-- 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력하는 SQL문
-- 저쟈 ID 오름차순, 카테고리 내림차순
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY,SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID AND SALES_DATE LIKE "2022-01%"
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC