-- 자동차 종류가 '트럭'인 자동차의 대여 기록
-- 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 
-- 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문
-- 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬
WITH TB AS (
  SELECT HISTORY_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DATEDIFF, C.DAILY_FEE, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE C.CAR_ID = H.CAR_ID AND CAR_TYPE = "트럭" 
)

SELECT HISTORY_ID, 
    CASE 
      WHEN DATEDIFF >= 90 THEN ROUND(DATEDIFF * DAILY_FEE * (1 - (CAST(REPLACE(DISCOUNT_RATE, '%', '') AS UNSIGNED) / 100)))
      WHEN DATEDIFF >= 30 THEN ROUND(DATEDIFF * DAILY_FEE * (1 - (CAST(REPLACE(DISCOUNT_RATE, '%', '') AS UNSIGNED) / 100)))
      WHEN DATEDIFF >= 7 THEN ROUND(DATEDIFF * DAILY_FEE * (1 - (CAST(REPLACE(DISCOUNT_RATE, '%', '') AS UNSIGNED) / 100)))
      ELSE DATEDIFF * DAILY_FEE
    END AS FEE
    
FROM TB T LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
         ON T.CAR_TYPE = P.CAR_TYPE
        AND (
             (P.DURATION_TYPE = '90일 이상' AND T.DATEDIFF >= 90) OR
             (P.DURATION_TYPE = '30일 이상' AND T.DATEDIFF >= 30 AND T.DATEDIFF < 90) OR
             (P.DURATION_TYPE = '7일 이상' AND T.DATEDIFF >= 7 AND T.DATEDIFF < 30)
            )
ORDER BY FEE DESC, HISTORY_ID DESC