-- 아이템의 희귀도가 'RARE'인 아이템들의 모든 다음 업그레이드 아이템의 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY
SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I, ITEM_TREE T
WHERE T.PARENT_ITEM_ID in (select II.ITEM_ID FROM ITEM_INFO II WHERE RARITY = "RARE") AND I.ITEM_ID = T.ITEM_ID
ORDER BY I.ITEM_ID DESC